before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    binary: cpf

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: darwin
        format: zip

brews:
  - name: cpf
    homepage: "https://github.com/diegopeixoto/go-cpf-cli"
    description: "A CLI tool to validate, format and generate Brazilian CPF numbers"
    license: "MIT"
    tap:
      owner: aquarela-io
      name: homebrew-cpf
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    install: |
      bin.install "cpf"
    test: |
      system "#{bin}/cpf", "--version"

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
